import { Product } from '@/types'

export const sampleProducts: Product[] = [
  {
    _id: '1',
    title: 'Garden Bliss Bouquet',
    slug: { current: 'garden-bliss-bouquet' },
    price: 125,
    shortDescription: 'A lush mix of peonies, garden roses, and eucalyptus',
    category: 'bouquets',
    inStock: true,
    featured: true,
    tags: ['peonies', 'roses', 'eucalyptus'],
    images: [],
  },
  {
    _id: '2',
    title: 'Côte d\'Azur Flower Box',
    slug: { current: 'cote-dazur-flower-box' },
    price: 185,
    shortDescription: 'French roses and delphiniums in an elegant hat box',
    category: 'flower-boxes',
    inStock: true,
    featured: true,
    tags: ['roses', 'delphiniums', 'box'],
    images: [],
  },
  {
    _id: '3',
    title: 'Rose Petal Romance',
    slug: { current: 'rose-petal-romance' },
    price: 95,
    shortDescription: '50 premium roses in soft blush and ivory tones',
    category: 'bouquets',
    inStock: true,
    featured: true,
    tags: ['roses'],
    images: [],
  },
  {
    _id: '4',
    title: 'Wildflower Meadow',
    slug: { current: 'wildflower-meadow' },
    price: 80,
    shortDescription: 'A free-spirited mix of seasonal wildflowers',
    category: 'bouquets',
    inStock: true,
    featured: false,
    tags: ['wildflowers', 'seasonal'],
    images: [],
  },
  {
    _id: '5',
    title: 'Luxe Bridal Arrangement',
    slug: { current: 'luxe-bridal-arrangement' },
    price: 350,
    shortDescription: 'An opulent wedding arrangement with white orchids and ranunculus',
    category: 'wedding',
    inStock: true,
    featured: false,
    tags: ['orchids', 'ranunculus', 'wedding'],
    images: [],
  },
  {
    _id: '6',
    title: 'Teddy Bear & Roses Bundle',
    slug: { current: 'teddy-bear-roses-bundle' },
    price: 140,
    shortDescription: 'A soft teddy bear paired with 12 premium red roses',
    category: 'gifts-balloons',
    inStock: true,
    featured: true,
    tags: ['gift', 'roses', 'teddy'],
    images: [],
  },
  {
    _id: '7',
    title: 'Sunrise Tulip Bouquet',
    slug: { current: 'sunrise-tulip-bouquet' },
    price: 70,
    shortDescription: 'Cheerful tulips in warm orange and yellow hues',
    category: 'bouquets',
    inStock: true,
    featured: false,
    tags: ['tulips'],
    images: [],
  },
  {
    _id: '8',
    title: 'Pink Champagne Box',
    slug: { current: 'pink-champagne-box' },
    price: 220,
    shortDescription: 'Blush spray roses and peonies in a premium keepsake box',
    category: 'flower-boxes',
    inStock: true,
    featured: true,
    tags: ['roses', 'peonies', 'box'],
    images: [],
  },
]
